/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "CALCULADORA.h"

int *
sumar_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->arg1 + argp->arg2;

	return &result;
}

int *
restar_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->arg1 - argp->arg2;

	return &result;
}

int *
multiplicar_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->arg1 * argp->arg2;

	return &result;
}

float *
dividir_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static float  result;

	if((argp->arg2) != 0){
		result = argp->arg1 / argp->arg2;
	}else{
		result = 0;
	}

	return &result;
}
