/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author aarongarcia
 */
public class VentanaHilo extends javax.swing.JPanel {

    /**
     * Creates new form VentanaHilo
     */
    public VentanaHilo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_titulo_hilo_previo = new javax.swing.JLabel();
        jLabel_numero_hilo_previo = new javax.swing.JLabel();
        jLabel_titulo_hilo_siguiente = new javax.swing.JLabel();
        jLabel_numero_hilo_siguiente = new javax.swing.JLabel();
        jLabel_titulo_hilo = new javax.swing.JLabel();
        jLabel_numero_hilo_actual = new javax.swing.JLabel();
        jLabel_titulo_separador = new javax.swing.JLabel();
        jLabel_numero_total_hilos = new javax.swing.JLabel();
        jLabel_titulo_nombre_archivo = new javax.swing.JLabel();
        jTextField_cadena_nombre_archivo = new javax.swing.JTextField();
        jButton_buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_estatus = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel_titulo_hilo_previo.setText("Hilo previo:");

        jLabel_numero_hilo_previo.setText("#");

        jLabel_titulo_hilo_siguiente.setText("Hilo siguiente: ");

        jLabel_numero_hilo_siguiente.setText("#");

        jLabel_titulo_hilo.setText("Hilo:");

        jLabel_numero_hilo_actual.setText("#");

        jLabel_titulo_separador.setText("-");

        jLabel_numero_total_hilos.setText("#");

        jLabel_titulo_nombre_archivo.setText("Archivo a buscar: ");

        jButton_buscar.setText("Buscar");

        jTextArea_estatus.setColumns(20);
        jTextArea_estatus.setRows(5);
        jScrollPane1.setViewportView(jTextArea_estatus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_titulo_nombre_archivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_cadena_nombre_archivo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_titulo_hilo_previo)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_numero_hilo_previo)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel_titulo_hilo_siguiente)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_numero_hilo_siguiente)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel_titulo_hilo)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_numero_hilo_actual)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_titulo_separador)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_numero_total_hilos))
                    .addComponent(jButton_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_titulo_hilo_previo)
                    .addComponent(jLabel_numero_hilo_previo)
                    .addComponent(jLabel_titulo_hilo_siguiente)
                    .addComponent(jLabel_numero_hilo_siguiente)
                    .addComponent(jLabel_titulo_hilo)
                    .addComponent(jLabel_numero_hilo_actual)
                    .addComponent(jLabel_titulo_separador)
                    .addComponent(jLabel_numero_total_hilos))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_titulo_nombre_archivo)
                    .addComponent(jTextField_cadena_nombre_archivo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_buscar;
    private javax.swing.JLabel jLabel_numero_hilo_actual;
    private javax.swing.JLabel jLabel_numero_hilo_previo;
    private javax.swing.JLabel jLabel_numero_hilo_siguiente;
    private javax.swing.JLabel jLabel_numero_total_hilos;
    private javax.swing.JLabel jLabel_titulo_hilo;
    private javax.swing.JLabel jLabel_titulo_hilo_previo;
    private javax.swing.JLabel jLabel_titulo_hilo_siguiente;
    private javax.swing.JLabel jLabel_titulo_nombre_archivo;
    private javax.swing.JLabel jLabel_titulo_separador;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_estatus;
    private javax.swing.JTextField jTextField_cadena_nombre_archivo;
    // End of variables declaration//GEN-END:variables
}
